apiVersion: v1
kind: Service
metadata:
  name: custom-dynamic-service
spec:
  selector:
    env: prod
  ports:
    - port: 8080      # na którym porcie serwis nasługuje ruchu
      targetPort: 80  # na który port serwis będzie kierował ruch

