apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1.0
  labels:
    environment: production

spec:
  replicas: 1
  selector:
    matchLabels:
      environment: production
  
  template:
    metadata:
      labels:
        environment: production
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80