apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:                         # nie musimy podawać typu     
  selector:
    env: prod
  ports:
    - protocol: TCP           # opcjonalna opcja
      port: 80    
      targetPort: 80  
  type: LoadBalancer