apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort      # ten parametr definiuje service type
  selector:
    env: prod
  ports:
    - port: 8080      # na którym porcie serwis nasługuje ruchu
      targetPort: 80  # na który port serwis będzie kierował ruch
      nodePort: 30107 # to jest port na którym serwis będzie wystawiony dla usera. Ten parametr jest opcjonalny, gdy go nie przypiszesz to k8s sam to zrobi
                      # to dobra praktyka aby wpisywać ten port ponieważ za każdym razem gdy zrestartujesz serwis to port się będzie odświeżał (co to znaczy?)