apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-test
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello this is Cron test
          restartPolicy: OnFailure