apiVersion: v1
kind: Pod
metadata:
  name: my-pod

spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: my-app
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume

  volumes:
    - name: test-volume
      hostPath:
        path: /data #directory on host
        type: Directory #optional